// Generated by CoffeeScript 1.6.2
(function() {
  var assert, _;

  assert = require("better-assert");
  _ = require("underscore");

  module.exports = _(assert).extend({
    "ok": function(x) {
      return assert(x);
    },
    "equal": function(x, y) {
      return assert(_.isEqual(x, y));
    },
    "empty": function(x) {
      return assert(_.isEmpty(x));
    },
    "element": function(x, y) {
      return assert(_.isElement(x, y));
    },
    "array": function(x) {
      return assert(_.isArray(x));
    },
    "object": function(x) {
      return assert(_.isObject(x));
    },
    "arguments": function(x) {
      return assert(_.isArguments(x));
    },
    "function": function(x) {
      return assert(_.isFunction(x));
    },
    "string": function(x) {
      return assert(_.isString(x));
    },
    "number": function(x) {
      return assert(_.isNumber(x));
    },
    "finite": function(x) {
      return assert(_.isFinite(x));
    },
    "boolean": function(x) {
      return assert(_.isBoolean(x));
    },
    "date": function(x) {
      return assert(_.isDate(x));
    },
    "regexp": function(x) {
      return assert(_.isRegExp(x));
    },
    "NaN": function(x) {
      return assert(_.isNaN(x));
    },
    "null": function(x) {
      return assert(_.isNull(x));
    },
    "undefined": function(x) {
      return assert(_.isUndefined(x));
    },
    "defined": function(x) {
      return assert(!_.isUndefined(x));
    }
  });

}).call(this);
